#!/bin/bash

echo "═══════════════════════════════════════════════════════════════"
echo "  ReflectivAI Worker Deployment Instructions"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "📋 PREREQUISITES:"
echo "1. Cloudflare account with Workers enabled"
echo "2. Wrangler CLI installed (✅ Already installed: v4.47.0)"
echo "3. Groq API keys (get from https://console.groq.com/keys)"
echo ""

echo "🔑 STEP 1: Authenticate with Cloudflare"
echo "Run: wrangler login"
echo "This will open a browser for authentication"
echo ""

echo "🔐 STEP 2: Set Secret Environment Variables"
echo "Run these commands (you'll be prompted to enter each key):"
echo ""
echo "  wrangler secret put PROVIDER_KEY"
echo "  wrangler secret put PROVIDER_KEY_2"
echo "  wrangler secret put PROVIDER_KEY_3"
echo ""
echo "Or use legacy names (also supported):"
echo "  wrangler secret put GROQ_API_KEY"
echo "  wrangler secret put GROQ_API_KEY_2"
echo "  wrangler secret put GROQ_API_KEY_3"
echo ""

echo "🚀 STEP 3: Deploy the Worker"
echo "Run: wrangler deploy"
echo ""

echo "✅ STEP 4: Verify Deployment"
echo "Test the version endpoint:"
echo "  curl https://my-chat-agent-v2.tonyabdelmalak.workers.dev/version"
echo ""
echo "Expected response: {\"version\":\"r10.1\"}"
echo ""

echo "📝 STEP 5: Test Sales Coach"
echo "Run this to test the Sales Coach format:"
echo ""
echo 'curl -X POST https://my-chat-agent-v2.tonyabdelmalak.workers.dev/chat \'
echo '  -H "Content-Type: application/json" \'
echo "  -d '{"
echo '    "mode": "sales-coach",'
echo '    "messages": [{"role": "user", "content": "How do I address HCP safety concerns?"}],'
echo '    "session": "test-123"'
echo "  }'"
echo ""

echo "Expected response should include:"
echo "  - Challenge:"
echo "  - Rep Approach: (with 3 bullets)"
echo "  - Impact:"
echo "  - Suggested Phrasing:"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  Configuration Summary"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Worker Name: my-chat-agent-v2"
echo "Worker File: worker.js (1687 lines)"
echo "Version: r10.1"
echo ""
echo "Environment Variables (from wrangler.toml):"
echo "  ✅ PROVIDER_URL = https://api.groq.com/openai/v1/chat/completions"
echo "  ✅ PROVIDER_MODEL = llama-3.1-8b-instant"
echo "  ✅ CORS_ORIGINS = (includes reflectivei.github.io, reflectivai.github.io, tonyabdelmalak.github.io)"
echo ""
echo "Secrets (must be set manually):"
echo "  ⚠️  PROVIDER_KEY (or GROQ_API_KEY)"
echo "  ⚠️  PROVIDER_KEY_2 (or GROQ_API_KEY_2)"
echo "  ⚠️  PROVIDER_KEY_3 (or GROQ_API_KEY_3)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🎯 QUICK START (if already authenticated):"
echo ""
echo "  # Set secrets (run each command, paste API key when prompted):"
echo "  wrangler secret put PROVIDER_KEY"
echo "  wrangler secret put PROVIDER_KEY_2"
echo "  wrangler secret put PROVIDER_KEY_3"
echo ""
echo "  # Deploy"
echo "  wrangler deploy"
echo ""
echo "  # Test"
echo "  curl https://my-chat-agent-v2.tonyabdelmalak.workers.dev/version"
echo ""
echo "═══════════════════════════════════════════════════════════════"
